Add bytecode compiler and runner
XuJiandong/ckb-js-vm pull request #11
Opened 2023-09-22 05:37 UTC by mohanson

2023-09-22 06:02 UTC, XuJiandong requested changes

2023-09-22 06:02 UTC, XuJiandong commented on quickjs/qjs.c
> +static int compile(JSContext *ctx, const void *buf, int buf_len) {
`compile` feature is not necessary. We can use native `qjsc`.

2023-09-22 06:02 UTC, XuJiandong commented on quickjs/qjs.c
> +        if (strcmp(argv[i], "-b") == 0) {
Try to guess byte code without flag.

2023-10-07 00:31 UTC, XuJiandong requested changes

2023-10-07 00:31 UTC, XuJiandong commented on quickjs/qjs.c
> +    if (((const char *)buf)[0] == (char)0x02) {
`0x02` can be defined as a macro.

2023-10-07 00:31 UTC, XuJiandong commented on tests/ckb_js_tests/Makefile
> +	cd ../../build/bytecode && lua ../../tools/fs.lua pack ../../build/testdata_fs_modules_bc.bin main.js fib_module.js
rename "*.js" to "*.bc".

2023-10-07 00:31 UTC, XuJiandong commented on quickjs/qjs.c
> +int compile_from_file_system(JSContext *ctx, const char* filename) {
I think "-c -f" options is not necessary. "-c" option is enough.

2023-10-07 01:39 UTC, XuJiandong commented on quickjs/qjs.c
> +int compile_from_file_system(JSContext *ctx, const char* filename) {
It can also be achieved by "-c". Compiling a file in file system is not necessary.

2023-10-07 01:56 UTC, mohanson commented on quickjs/qjs.c
> +int compile_from_file_system(JSContext *ctx, const char* filename) {
If the javascript code imports a module (`import { fib } from "./fib_module.js"`, eg), we cannot compile it without telling it the contents of `fib_module.js`, therefore a file system is necessary

2023-10-07 09:12 UTC, XuJiandong approved these changes

2023-10-07 09:12 UTC, merged